export const metaKeywords =[
  "Online Marketplace",
  "E-commerce Platform",
  "Multi-Vendor Marketplace",
  "Shop Online",
  "Buy and Sell",
  "Unique Products",
  "Local Vendors",
  "Global Sellers",
  "Fashion Accessories",
  "Electronics",
  "Home Decor",
  "Handmade Crafts",
  "Vintage Goods",
  "Health and Beauty",
  "Toys and Games",
  "Electronics Gadgets",
  "Jewelry Collection",
  "Artisanal Products",
  "Kitchen Appliances",
  "Outdoor Gear",
  "Tech Deals",
  "Mobile Accessories",
  "Fashion Trends",
  "Discount Shopping",
  "Daily Deals",
  "Gift Ideas",
  "Affordable Prices",
  "Quality Products",
  "Customer Reviews",
  "Secure Payments",
  "Fast Shipping",
  "Fashion Apparel",
  "Home Essentials",
  "DIY Supplies",
  "Unique Gifts",
  "Handcrafted Jewelry",
  "Designer Clothing",
  "Health Supplements",
  "Beauty Products",
  "Kids Toys",
  "Pet Supplies",
  "Sports Equipment",
  "Electronics Store",
  "Home Improvement",
  "Vintage Clothing",
  "Local Artisans",
  "Craftsmanship",
  "Outdoor Adventures",
  "Tech Accessories",
  "Mobile Phones",
  "Trendy Fashion",
  "Exclusive Deals",
  "Gifts for Her",
  "Gifts for Him",
  "Best Sellers",
  "Fashion Brands",
  "Home Furnishings",
  "DIY Projects",
  "Artistic Creations",
  "Luxury Items",
  "Healthy Living",
  "Cosmetics",
  "Educational Toys",
  "Pet Care Products",
  "Athletic Gear",
  "Electronics Deals",
  "Smart Home Devices",
  "Vintage Collectibles",
  "Local Handmade Goods",
  "Customized Jewelry",
  "Designer Brands",
  "Wellness Products",
  "Children's Toys",
  "Outdoor Lifestyle",
  "Gadget Accessories",
  "Cell Phones",
  "Fashionable Clothing",
  "Flash Sales",
  "Personalized Gifts",
  "Top Picks",
  "Home Decor Ideas",
  "Craft Supplies",
  "Artisanal Crafts",
  "Premium Fashion",
  "Natural Beauty",
  "Toys for Kids",
  "Pet Lovers",
  "Fitness Equipment",
  "Electronics Sale",
  "Smart Gadgets",
  "Retro Fashion",
  "Local Artistry",
  "Handmade Jewelry",
  "Luxury Fashion",
  "Organic Products",
  "Educational Games",
  "Pet Toys",
  "Outdoor Gear Sale",
  "Phone Accessories",
  "Trendy Gadgets",
  "Clothing Brands",
  "Home Design",
  "Creative Crafts",
  "Fashionista Finds",
  "Unique Home Decor",
  "DIY Inspiration"
]